### PR TITLE
Release 1.0.0

### PR DESCRIPTION
**Pull request by andyperlitch**
Opening this for the community to weigh in on.

### CODE REVIEW

**Comment by awashbrook** [comment]
Thanks Andy,

Thanks for all your hard work on 1.0.0, we are working on adoption
internally at present.

Pleased to see minimise make it in, how about full screen?

Let me take a look at the other feature enhancements over the weekend :)

**Comment by robertmazzo** [comment]
gents,
I am experimenting with a simple solution to the Maximize feature.
In the dashboard.html template, I include a new span element before Andy's new minimize span:

<span title="maximize" ng-show="widget.gadgetConfigured" ng-click="maxResizer($event)" class="glyphicon glyphicon-resize-full"></span>

In the directive code, I added $scope.maxResizer (not entirely different frmo say grabResizer) :

       ```$scope.maxResizer = function (e) {
            var widget = $scope.widget;
            var widgetElm = $element.find('.widget');          
            var ht_diff = 200;  // (set to zero if you want the entire height of screen to be used)

            // TODO: properly restore the window to original position..

            widget.setWidth(window.innerWidth);
            $scope.widget.setHeight(window.innerHeight-ht_diff);

            $scope.$emit('widgetChanged', widget);
           
            $scope.$broadcast('widgetResized', {
                width: window.innerWidth,
                height: window.innerHeight-ht_diff
            });
        }```

The trick now is to figure out how to change the icon to a "Restore" type icon, and have the widget size revert to original size.

I hope I can finish it soon.
thanks,
Bob

**Comment by andyperlitch** [comment]
Just wanted to post something here: **the 1.0.0 tag has a bug that breaks the library**. I have since fixed it and pushed v1.0.1 to master. I plan on also retroactively fixing it for the v1.0.0 tag, but wanted to let everyone know about it in case they tried upgrading prior to 1.0.1. Sorry for the mess-up!

**Comment by robertmazzo** [comment]
where's the best place to reopen the maximize icon feature in the widget header options ?
I already started coding something up. 
Would I be creating a new PR for that ?
thanks.
Bob

**Comment by awashbrook** [comment]
@robertmazzo when you're ready please link your maximize PR to https://github.com/DataTorrent/malhar-angular-dashboard/issues/48

**Pull request merged**
