### PR TITLE
Compatible to angular-bootstrap 0.14.3

### PR DESCRIPTION
**Pull request by Exotelis**
* angular-bootstrap version is now 0.14.3

* added uib- prefix

### CODE REVIEW

**Comment by andyperlitch** [comment]
hmm... peerDependencies warning. These have always confounded me

**Comment by Exotelis** [comment]
It's working with 
´´´node_js:
  - '4.1'
´´´

**Comment by Exotelis** [comment]
It's working if I update .travis.yml
```
node_js:
  - '4.1'
```

**Comment by Exotelis** [comment]
Best option to fix this is to upgrade npm to version 4.2.0

```
node_js:
  - '4.2.0'
```

**Pull request closed without merging**
