### PR TITLE
support latest version of angular-ui-bootstrap

### PR DESCRIPTION
**Pull request by Exotelis**

### CODE REVIEW

**Comment by sashadt** [comment]
@jessicawangdt is reviewing this request now, and will merge when ready.  @Exotelis thanks for contributing!

**Comment by jessicawangdt** [comment]
@Exotelis : When testing this PR by running simplest demo ("gulp serve"), an error appears:

Unknown provider: $animateCssProvider <- $animateCss <- $uibModalStack <- $uibModal <- dashboardDirective

I fixed this error by upgrading "angular": "~1.3" to "angular": "~1.4"
 
I also changed angular-mocks version to match angular version.
i.e. upgrading "angular-mocks": "~1.3" to "angular-mocks": "~1.4".

I opened another PR that includes this PR and my fixes for this PR:
https://github.com/DataTorrent/malhar-angular-dashboard/pull/164

**Comment by Exotelis** [comment]
Hi @jessicawangdt Thank you for reviewing

Yes you are right. 
angular-bootstrap >= 1.0.0 depends on angular >= 1.4.4. My bad

**Comment by sashadt** [comment]
This PR has been resolved with https://github.com/DataTorrent/malhar-angular-dashboard/pull/164

**Pull request closed without merging**
