### PR TITLE
(1) updated dashboard component to enforce minWidth settings. (2) upd…

### PR DESCRIPTION
**Pull request by wvary**
…ated dashboard component to apply width/minWidth on browser resize. (3) Refactored GrabSizer to support horizontal and vertical resizing. (4) added CartDataModel to be used in dynamic data examples. (5) added examples to demonstrate refreshing widgets with dynamic options. (6) added examples to demonstrate refreshing widgets with dynamic data. (7) added resize examples to demonstrate with minWidth support. (8) added coverage report to test. (9) added/updated unit tests for complete code coverage.

Resolve issue #140 (demonstrated by item 7)
Resolve issue #137 (demonstrated by item 6)
Resolve issue #136 (demonstrated by item 5)
Resolve issue #126 (demonstrated by item 6)

### CODE REVIEW

**Comment by wvary** [comment]
@mohini-sri90 Please review PR when you have a chance, thanks.

**Comment by sashadt** [comment]
A few review comments:

1.  When title doesn't fit the widget width, we should not let controls (on top right) overflow to the next level.  They should always stay in the top right corner.  Title text should be abbreviated by "..." ellipsis.

2.  Slight delay (3-4 sec) when widget of fixed percentage width is resized due to browser window size changes.

3.  [Optional] Improve behavior when resizing past the minimum width limit.  Do not let the outline go past minimum width.

4.  [New Feature] Resizing from corner is not possible today - would make things much easier if X and Y dimensions could be resized at the same time.

5.  Could be useful to have min height in addition to min width.

**Comment by wvary** [comment]
Regarding point #2, it's by design.  The widget option set in the application sets a delay of 2 seconds to demonstrates such feature.

**Comment by sashadt** [comment]
Let's remove the delay from the demo.

**Comment by wvary** [comment]
@sashadt This is ready for another round of review.

**Pull request merged**
